.github/workflows/lighthouse.yml, lighthouserc.yml, pages/building-block-info.js, pages/index.js
=> Lighthouse in CI

pages/index.js, pages/partner-with-us.js, pages/product-offerings.js
Matt added some content changes to the webpage. Also added the links to learn more
=> Content changes

README.md
Added an overview of the website with tools use such as NextJS as well as the accessibility considerations in the design and CI
=> Readme changes with overview and accessibility

components/product-offerings/building-blocks-links.js
=> Fix broken link to record linkage docs

pages/partner-with-us.js, styles/globals.css
Update partner with us page content to new designs.
Fixes [#904](https://github.com/CDCgov/phdi/issues/904)
=> Update partner with us content

pages/about.js
We don't have links for the documents on the "About" page yet, so commenting them out for now. Also made an apostrophe fix and added some content that I think was accidentally cut.
=> Temp fix for the static site "about" page

components/products/building-blocks-links.js, pages/about.js, pages/index.js, pages/products.js
Made a few revisions (primarily replaced "starter kit" with "DIBBs pipeline"
=> Content revisions

pages/about.js
Fixing the spacing between the strategy link and the next word
Not sure why all the formatting got changed, but you only need to pay attention to line 36
=> fixing spacing for matt

.github/workflows/docker-build.yml
Adds a user triggered workflow to publish dev and staging packages
=> Add workflow to publish packages for dev and staging

src/app/case-studies/dibbs-prototype/page.tsx, src/app/case-studies/page.tsx
This PR adds the DIBBs Prototype case study page, accessible at [http://localhost:3000/case-studies/dibbs-prototype](http://localhost:3000/case-studies/dibbs-prototype).
=> Create DIBBs Prototype case study page

next.config.js, src/app/_styles/Homepage.module.scss, src/app/components/Footer/Footer.module.scss, src/app/components/Footer/Footer.tsx, src/app/components/InvitationCta/InvitationCta.module.scss, src/app/components/InvitationCta/InvitationCta.tsx, src/app/custom-styles.css, src/app/data/home.ts, src/app/page.tsx
Adds the background image to the interested homepage section.
=> Style interested section

src/app/components/Footer/Footer.tsx, src/app/components/Header/Header.tsx, src/app/components/NavigationLink/NavigationLink.tsx
Just a temporary fix so the mobile menu is at least usable.
We'll style when we have designs.
=> fixes mobile menu

src/app/components/Footer/Footer.tsx, src/app/components/NavigationLink/NavigationLink.tsx
Footer items shouldn't have active underlines
=> remove underline from footer nav items

src/app/engage-with-us/page.tsx, src/app/engage-with-us/styles.scss
This PR should address the following items from the [QA list](https://docs.google.com/document/d/1HYsAwva0_VEj40uxqkBl2boglNTcG1_y3lbdsaIpJE4/edit):
=> "Engage with us" punch list items

src/app/components/Carousel/Carousel.tsx
Tweaking the carousel to handle mobile views and smaller widths better
=> Some tweaks to the carousel

src/app/components/NavigationLink/NavigationLink.tsx, src/app/products/page.tsx, src/app/uswds-settings.scss
This PR updates the various different default link state colors according to the [Figma designs](https://www.figma.com/design/3VaLNvirF5Tq2RFHsD32g1/dibbs.cdc.gov?node-id=3192-26197&m=dev).
=> Update link state color defaults

src/app/products/ecr-viewer/page.tsx
This PR updates the border color of the [FAQ accordion items](https://www.figma.com/design/3VaLNvirF5Tq2RFHsD32g1/dibbs.cdc.gov?node-id=2256-27986&m=dev) on the eCR Viewer product page.
=> Update FAQ item border color on hover

package-lock.json, package.json, src/app/api/contact/route.ts, src/app/engage-with-us/components/ContactForm.tsx
This PR removes the inquiry field from the form. It also adds some additional server side validation using Zod.
=> Remove inquiry option from engage with us form

src/app/products/_ui/index.tsx, src/app/products/ecr-viewer/page.tsx, src/app/products/query-connector/page.tsx
This PR primarily improves the product detail page's image scaling to work better across displays. However, it also includes some clean up and minor styling changes to the image components.
=> Improve product detail page image scaling

src/app/products/_ui/index.tsx
This PR adds padding to the top of the product detail page nav regardless of display.
=> Improve product detail page nav padding for all displays

src/app/products/_ui/index.tsx, src/app/products/ecr-viewer/page.tsx
This PR addresses some basic a11y issues caught by [axe devtools](https://chromewebstore.google.com/detail/axe-devtools-web-accessib/lhdoppojpmngadmnindnejefpokejbdd?hl=en-US).
=> A11y testing and corrections

src/app/engage-with-us/__tests__/page.test.tsx, src/app/engage-with-us/components/ContactForm.tsx, src/app/products/_ui/index.tsx, src/app/products/ecr-viewer/page.tsx, src/app/products/query-connector/page.tsx
This PR correct spelling mistakes and other minor content related issues.
=> Content updates based on review

src/app/case-studies/_cloud-hosting/page.tsx, src/app/case-studies/_ecr-viewer/page.tsx, src/app/case-studies/dibbs-pipeline/page.tsx, src/app/case-studies/dibbs-prototype/page.tsx, src/app/case-studies/page.tsx, src/app/engage-with-us/page.tsx, src/app/page.tsx, src/app/products/ecr-viewer/page.tsx, src/app/products/page.tsx, src/app/products/query-connector/page.tsx
This PR adds a meta description for all site pages.
=> Add meta descriptions to all pages
