components/product-offerings/building-blocks-links.js, components/product-offerings/software-development-kit-info.js
They need a specific release tag for the links to work.
=> Update building block API links

README.md, components/NavbarUSWDS/NavbarUSWDS.js, next.config.js
Resolves https://github.com/CDCgov/phdi/issues/940
Change the url to be `/dibbs-site` rather than `/phdi-site`
=> update links to dibbs-site

pages/about.js
The DIBBs site links to an old PRIME document. This pull request updates the page to link to the current Public Health Data Strategy located at https://www.cdc.gov/ophdst/public-health-data-strategy/
=> Update Public Health Data Strategy link to point to current version

.eslintrc.json, .github/workflows/lighthouse.yml, .github/workflows/pages.yml, .prettierrc, akamai-loader.js, lighthouserc.yml, next.config.js, package-lock.json, package.json, src/app/components/Footer.tsx, src/app/components/Header.tsx, src/app/components/MarkdownComponent.tsx, src/app/components/NavigationLink.tsx, src/app/components/UsaBanner.tsx, src/app/globals.css, src/app/layout.tsx, src/app/our-products/page.tsx, src/app/page.tsx, src/app/product-detail/page.tsx, src/app/resources/page.tsx, src/app/styles/Home.module.scss, src/app/utils/constants.ts, src/app/utils/markdown.ts, tailwind.config.ts
This PR does the following:
- Adds and makes use of `classNames` where appropriate
- Adds some reasonable defaults for `prettier` and `eslint`
- A couple of new `devDependencies` were added for this 
- Formats all applicable files using the new `prettier` defaults
- Ensures the `Footer` component renders a `footer` element rather than another `header`
- Moves `NavigationLink` and its prop type into its own file
- Moved the heavily used `basePath` variable into its own `constants.ts` file
- Fixed an error where Next.js couldn't find the `favicon.ico`
- Some other minor cleanup 
1. Run `npm i` to install the new packages
2. Start the project (restart might be needed)
3. Make sure everything generally still works and looks the same
If you happen to run into any issues, it might be worth …
=> Incorporate classnames package and do some general cleanup

src/app/components/NavigationLink/NavigationLink.tsx
This PR ensures that `aria-current="page"` is added to the link element of the page we're currently looking at. Additionally, I've slightly modified the `NavigationLink` so that navigating to child pages will allow the  top-level parent page's nav link to remain underlined.
For example, navigating to the `/products/ecr-viewer` page will keep the `Our products` link underlined in the nav.
=> Add 'aria-current' to selected nav item

src/app/case-studies/page.tsx, src/app/components/Header/Header.tsx, src/app/context/index.tsx, src/app/data/home.ts, src/app/engage-with-us/page.tsx, src/app/hooks/useHeroInit.ts, src/app/layout.tsx, src/app/page.tsx, src/app/products/page.tsx
Use context so header content is with their pages
=> Use context for header

src/app/case-studies/la-county/page.tsx, src/app/case-studies/la-county/styles.scss, src/app/case-studies/page.tsx, src/app/custom-styles.css
This PR adds the first case study page layout.
=> LA County case studies page layout

.vscode/extensions.json, .vscode/settings.json, src/app/hooks/useHeroInit.ts
This PR adjusts the shared VS Code `settings.json` so that ESLint warnings and errors will now appear within the VS Code editor when using the [ESLint extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint).
Here's an example (which I've fixed in this PR):
=> Update workspace settings to show linting warnings/errors in editor

src/app/case-studies/_ui/index.tsx, src/app/case-studies/_ui/styles.module.scss, src/app/case-studies/cloud-hosting/page.tsx, src/app/case-studies/dibbs-pipeline/page.tsx, src/app/case-studies/page.tsx
This PR:
- Adds the Cloud Hosting case study page and content
- Updates link to this new page from the case studies page (`/case-studies`)
- Fixes a small issue with the `UnorderedList` styling
=> Create Cloud Hosting case study page

src/app/components/RoundedBackground/RoundedBackground.tsx, src/app/engage-with-us/page.tsx
This PR updates the engage with us page to more closely match the design in Figma. I've also ensured the design is responsive (although this aspect may not be finalized until we review with UX).
Please check that:
- Style matches Figma
- Page works well on smaller display
=> Style "engage with us" page to match design

src/app/custom-styles.css
This PR addresses these items from the [QA checklist](https://docs.google.com/document/d/1HYsAwva0_VEj40uxqkBl2boglNTcG1_y3lbdsaIpJE4/edit?tab=t.0):
Note: we'll need to remove a lot of the local header/font styling for these changes to show up in the browser. That'll be a different PR.
=> Fix global typography styling

tailwind.config.ts
This PR lowers the font-weight of `font-semibold` from 600 to 599. It was noted in the [QA checklist](https://docs.google.com/document/d/1HYsAwva0_VEj40uxqkBl2boglNTcG1_y3lbdsaIpJE4/edit?tab=t.0#heading=h.xbdj3tqn9oml) that semibold font looks too bold.
600 does appear to be overly bold while dropping it to 599 looks more in-line with the Figma design.
Before:
After:
=> Lower font-weight value for Tailwind 'font-semibold'

src/app/components/LinkButton/LaunchIcon.tsx, src/app/components/LinkButton/LinkButton.tsx, src/app/products/query-connector/page.tsx
This PR finalizes the Query Connector product detail page's Demo section content based on the Figma design.
Here is what it looks like on the page:
=> Finalize the Query Connector demo section

src/app/products/_ui/index.tsx, src/app/products/query-connector/page.tsx
This PR adds the `Become a pilot partner` link button to the Query Connector product detail page. This link button will link users to the `/engage-with-us` form. I've also cleaned up the [`Development status`](https://www.figma.com/design/3VaLNvirF5Tq2RFHsD32g1/dibbs.cdc.gov?node-id=2432-2857&m=dev) section content.
=> Add "become a pilot partner" button to Query Connector page

src/app/components/Footer/Footer.tsx
This PR addresses an issue where the CDC logo would not display correctly in a live (prod build) environment.
=> Fix footer logo not loading in correctly

src/app/case-studies/_ui/index.tsx, src/app/components/Header/Header.tsx, src/app/engage-with-us/components/CustomerTestimonial.tsx, src/app/engage-with-us/page.tsx, src/app/page.tsx, src/app/products/_ui/index.tsx, src/app/products/page.tsx
This PR:
- Makes horizontal padding consistent across pages on smaller displays
- Adds some bottom padding to the header on small displays
- Fixes an a11y issue on the products page by ensuring links are distinguishable from other text
- Fixes an issue with the size of the customer testimonial on the `Engage with us` page
=> Continued responsiveness improvements

src/app/products/_ui/index.tsx, src/app/products/ecr-viewer/page.tsx
This PR updates the `Have a question that isn't answered above?` section of the product detail pages to include a `LinkButton` that navigates the user to the `engage with us` page.
It also adds links to the `engage with us` page from eCR Viewer's FAQ accordion items.
=> Add link buttons to engage with us page at bottom of product detail pages

src/app/case-studies/_cloud-hosting/page.tsx, src/app/case-studies/_ecr-viewer/page.tsx, src/app/case-studies/dibbs-pipeline/page.tsx, src/app/case-studies/dibbs-prototype/page.tsx, src/app/case-studies/page.tsx, src/app/engage-with-us/page.tsx, src/app/page.tsx, src/app/products/ecr-viewer/page.tsx, src/app/products/page.tsx, src/app/products/query-connector/page.tsx
This PR updates all page title meta tags to include `- DIBBs` at the end. This should help make the purpose of the site and its pages much more obvious.
=> Page title meta tags should include DIBBs branding

src/app/case-studies/page.tsx, src/app/products/ecr-viewer/page.tsx, src/app/products/page.tsx
This PR modifies a few of the page's titles to match the casing with the nav links on the site.
I've also improved styling reusability of the eCR Viewer FAQ section, which should have no visible changes.
=> Fix page title casing

components/NavbarUSWDS/NavbarUSWDS.js
This PR adds a banner with the text about site maintenance that we have been directed to add by  CDC stakeholders.
=> Adding banner with required language about government shutdown
